[package]
name = "nft-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Stellar/Soroban NFT standard contract with royalty support."

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = false
strip = true
lto = true
codegen-units = 1
